### ISSUE TITLE
./configure problem

### ISSUE THREAD

**Issue by ThePreviousOne** [DIGImend/uclogic-tools#4] opened 2018-02-10 20:21 UTC
./configure: line 3594: syntax error near unexpected token `LIBUSB,'
./configure: line 3594: `PKG_CHECK_MODULES(LIBUSB, libusb-1.0 >= 1.0.0)'

I am running debian testing and have version libusb-1.0 1.0.1
Looking around I found that pkg-config is needed to compile this so I have that also

Stable has the same problem

**Comment by spbnick** [comment] 2018-03-18 09:44
Thank you for the report, Greg. I added a note about pkg-config to README.md in 186140b. Would this be the fix you were looking for?

**Comment by rubypanther** [comment] 2018-11-01 00:06
I had the same problem, I tracked down the cause to having a newer copy of autotools in /usr/local
That causes aclocal to not find the macros.
It works if I run it as
`PATH=/usr/bin ./bootstrap`
but also adding the path to the aclocal call in bootstrap fixes it:
`aclocal -I /usr/share/aclocal`
which might not be portable. I don't normally have this problem and I compile a lot of packages from source, so presumably the normal more complete autotools setup finds it.

**Comment by spbnick** [comment] 2018-11-18 16:28
@rubypanther, I just removed `bootstrap` and replaced it with the instructions for running `autoreconf -i -f`. That should take care of the problem, hopefully.

@ThePreviousOne, I assume the README.md update is a suitable solution for you, since you don't reply, and am closing the issue.

**Closed as completed by spbnick** 2018-11-18 16:28 UTC
